"""Turn the imported BS Deluxe payload into a C source the hosts link in.

The payload has to ship in every download and the game must never fail to
launch over it, so it is compiled into the executable rather than looked up
next to it. `FzeroDeluxePrepare` verifies these bytes exactly as it verifies a
file, so a truncated or wrong-version embed is refused like any other.

    py -3 tools/embed_payload.py <bs-deluxe.dat> <out.c>
"""
import sys
from pathlib import Path

MAGIC = b"BSDELX1\0"


def main(source, destination):
    data = Path(source).read_bytes()
    if len(data) < 80 or not data.startswith(MAGIC):
        raise SystemExit("%s is not a BS Deluxe payload" % source)
    out = ["/* Generated by tools/embed_payload.py from %s. Do not edit. */\n"
           % Path(source).name,
           "#include <stddef.h>\n#include <stdint.h>\n\n",
           "const uint8_t fzero_deluxe_payload[] = {\n"]
    for start in range(0, len(data), 24):
        row = data[start:start + 24]
        out.append("".join("%d," % byte for byte in row))
        out.append("\n")
    out.append("};\nconst size_t fzero_deluxe_payload_size = sizeof(fzero_deluxe_payload);\n")
    text = "".join(out)
    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)
    # Leave the timestamp alone when nothing changed, so a reconfigure does not
    # force every host to relink.
    if not target.exists() or target.read_text() != text:
        target.write_text(text)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
